---
title: "How Do Self-Employed Software Developers Invest in Their Career?"
subtitle: "Philip Morgan Consulting Research Briefing"
author: "Philip Morgan"
date: November 5, 2019 - v1.0
abstract: |
  A study of how self-employed software developers invest in their careers, and where they believe career opportunity comes from, by Philip Morgan Consulting.
  
  
  The question that motivated this study: How do self-employed software developers invest in their career?
  The answer: It's pretty much what you might think, but there are some surprises.
fontsize: 13pt
urlcolor: blue
output:
  tufte::tufte_html:
    toc: true
    toc_depth: 2
  tufte::tufte_handout:
    toc: true
    toc_depth: 2
---

\newpage
# Key Findings

1. My study participants -- self-employed software developers -- strongly prefer individual, asynchronous learning styles (books and courses, primarily) over group, synchronous styles (realtime courses or mentoring). IRL conferences are the primary exception to this pattern.
2. New business opportunity for this group comes from relationships (networking and past clients), paying attention to changes in the market, and persistence in pursuing opportunity.
3. Two currently "hot" career investment tools (listening to podcasts and mentorship) are used at surprisingly low levels within my sample group.
4. While speaking and publishing are reliable opportunity-generators, they are used at relatively low levels by my sample group.

# Three questions

There are three specific questions from the survey that I'll focus on in this report

## 1) How do you invest in technical skills? 

`r tufte::margin_note('The full question was: Please list ways you have you spent time and money for developing your technical skills.')`

I standardized these responses to survey questions using a simple coding system: a response starting with "a-" is an action, while one starting with "s-" is a sentiment or belief. 

What you'll see below are the top 3 responses from each of my sample groups (one was recruited from LinkedIn, the other from my email list, more details in the Methodology section), and how many of my respondents indicated that action, sentiment, or belief, and what percentage of the total number of survey completions that number represents (rounded to the nearest whole number).

| LinkedIn Sample | List Sample |
|:--------------|:-----------|
| a-online-courses - 12 - 55% | a-online-courses - 22 - 67% |
| a-reading-books - 4 - 18%  | a-reading-books - 16 - 48% |
| a-irl-conferences - 4 - 18%" | a-coding-practice - 9 - 27% |

\newpage
## 2) How do you invest in business skills?

`r tufte::margin_note('The full question was: Please list ways you have you spent time and money for business or self-employment skills.')`

| LinkedIn Sample | List Sample |
|:--------------|:-----------|
| a-reading-books - 2 - 9% | a-online-courses - 15 - 45% |
| a-learning - 2 - 9% | a-reading-books - 15 - 45% |
| a-experimenting - 2 - 9% | a-email-lists - 6 - 18% |

## 3) Where does opportunity come from?

`r tufte::margin_note('The full question was: Consider your entire career as a self-employed software developer and times you have gotten new opportunities, better projects, or other forms of career improvement. What do you think led to these improvements in your career?')`

| LinkedIn Sample | List Sample |
|:--------------|:-----------|
| a-networking - 7 - 32% | a-networking - 8 - 24% |
| s-perceptiveness - 3 - 14% | a-relationships - 5 - 15% |
| s-persistence - 2 - 9% | a-relationship-with-existing-clients - 4 - 12% |

# Surprises

> Q: How do you invest in your career?
> 
> A: I buy books, courses, attend events, practice what I learn from those sources, and invest in my network to make sure I have future opportunity.

That answer is about the least surprising possible answer to the "how do you invest" question. And it is a good summary of what my survey responses indicate.

As I said at the top of this report, "it's pretty much what you'd think". There are indeed few surprises in the top 3 responses to each question. 

I'm also not surprised at the methods of career investment that were on the list but were relatively unpopular, specifically:

- Publishing
- Speaking

These are well-established -- we might use the over-used word *proven* -- methods of gaining visibility and cultivating authority. But they're also not easy to use. It's easier to read a book than write one -- or even a well-executed blog post -- and it's easier to consume a talk than get yourself on the stage and give a talk.

Despite the effectiveness of these career investment tools, it's no surprise that they're close to the bottom of the pile in terms of popularity. They're a ton of work. In fact, their relative unpopularity might explain their continued effectiveness: in a world where nearly everybody can give a killer talk, killer talks are not going to help you stand out. But in the actual world we live in, killer talks are rare, and lead to visibility and authority.

Here's another interesting way to interrogate this data: _what's not on the list of responses at all, or what's much further towards the bottom than we'd expect?_

Twitter gives us a certain filtered picture of the world of software development, and my Twitter feed currently has a lot of content about the value of mentorship, along with heated blowback against companies that place low value on mentorship. Yet, in my research, mentorship is represented either very minimally (1 of 33 list respondents) or not at all (my LinkedIn sample) as a career investment method. 

This is a surprising disconnect between the picture of the world Twitter offers, and the picture my research offers, which portrays software developers as very motivated to use individual learning methods (books, courses) and not very motivated at all to use more collaborative learning methods (mentorship, pair programming, online groups). 

To be fair, the Twitter hype train around mentorship is clearly in the context of regular employment, not self-employment. Yet if mentorship was broadly valuable, wouldn't self-employed people -- who enjoy relatively more freedom in the design of their work and career and therefore might have more ability to forge mentorship relationships -- seek it out more than is represented in my data? Is mentorship's value highest in the world of regular employment and relatively lower in self-employment?

Listening to podcasts -- as a career investment tool -- feels underrepresented in my data. I say "feels" because I haven't measured how often my friends, colleagues, clients, and the press mention listening to podcasts, but going on my subjective experience alone, I'd give it a top-3 ranking among possible methods of career investment. Yet my data ranks it lower. Not dramatically lower, mind you. In my list sample, it ranked 8 and 4 respectively among methods for investing in technical and career skills, and did not appear at all in my LinkedIn sample. Even so, the disparity between my subjective experience of hearing "podcasting, podcasting, podcasting" and my somewhat more objective experience of seeing it represented at a relatively low level in my data is jarring, and leads to further questions. ^[Chief among these questions would be whether there's a correlation between the activity of podcast listening and some measurable career outcome or achievement. Another question would be whether books and courses are viewed as "pure" learning tools while podcasts might be seen more as "info-tainment" tools.]

# Insights

What insights emerge from this slice of the data? 
There are at least two.

## Insight 1: Opportunity comes from relationships and market awareness.

As I often like to say: unfortunately, you're in a relationship business. My survey data bears this out.

In fact, when I dig into the full-resolution picture of where my respondents believe opportunity comes from, a clear pattern emerges: 

**Relationship assets outperform technical skill assets.**

Below is the full ranked list of coded responses to the question: "Consider your entire career as a self-employed software developer and times you have gotten new opportunities, better projects, or other forms of career improvement. What do you think led to these improvements in your career?"

I've bolded the responses that indicate relationship assets, and italicized those that indicate technical skill assets. The number to the right of each line is the number of respondents who indicated that action or sentiment:

| LinkedIn Sample | List Sample |
|:--------------|:-----------|
| 	**a-networking - 7**	 | 	**a-networking - 8**	 |
| 	**s-perceptiveness - 3**	 | 	**a-relationships - 5**	 |
| 	s-persistence - 2	 | 	**a-relationship-with-existing-clients - 4**	 |
| 	*s-focus-on-quality - 2*	 | 	s-luck - 4	 |
| 	**s-connections - 2**	 | 	a-focus-on-expensive-problems - 3	 |
| 	*s-skill - 1*	 | 	s-confidence - 3	 |
| 	*s-problemsolving-ability - 1*	 | 	*a-certification - 2*	 |
| 	s-positive-attitude - 1	 | 	a-building-confidence - 2	 |
| 	s-openness - 1	 | 	a-intentional-client-work - 2	 |
| 	**s-networking - 1**	 | 	a-marketing - 2	 |
| 	s-longevity - 1	 | 	a-mentoring - 2	 |
| 	*s-legacy-orientation - 1*	 | 	a-sales - 2	 |
| 	s-focus - 1	 | 	*a-skill-growth - 2*	 |
| 	s-curiosity - 1	 | 	a-being-where-opportunities-are - 1	 |
| 	*s-continuous-improvement - 1*	 | 	*a-continuous-improvement - 1*	 |
| 	s-coincidence - 2	 | 	a-discipline - 1	 |
| 	s-challenging-competetive-environment - 1	 | 	*a-doing-good-work - 1*	 |
| 	a-speaking - 1	 | 	a-exceeding-comfort-zone - 1	 |
| 	a-recruiters - 1	 | 	a-experiential-learning - 1	 |
| 	a-publishing - 1	 | 	*a-focus-on-hot-technologies - 1*	 |
| 		 | 	a-niche-visibility - 1	 |
| 		 | 	a-podcasts - 1	 |
| 		 | 	a-portfolio-or-case-studies - 1	 |
| 		 | 	a-publishing - 1	 |
| 		 | 	a-reading-books - 1	 |
| 		 | 	a-risk-taking - 1	 |
| 		 | 	a-service - 1	 |
| 		 | 	a-specializing - 1	 |
| 		 | 	*a-tech-skill - 1*	 |
| 		 | 	a-visibility - 1	 |
| 		 | 	s-divine-intervention - 1	 |
| 		 | 	s-mindset - 1	 |
| 		 | 	s-tough-streak - 1	 |
				 |
In the LinkedIn sample the differentiation between relationship and technical skill assets is not as obvious as in my email list sample, but the pattern is there in both samples: relationship assets (networking, maintaining relationships with past clients, and actively building a network) are more commonly listed as sources of opportunity than technical skills.

An interesting and relevant followup study would focus on the ROI of some of these career assets. This would add nuance that's currently missing from my data.

## Insight 2: We have to wonder, are devs choosing the most effective learning modes?

My data shows a clear preference for individual, asynchronous means of learning or career investment. For example, on every question focused on career investment, books, online courses, and individual practice are the most popular forms of investment. These are all generally done on an individual basis, and can be consumed asynchronously. In one instance (the LinkedIn Sample, the question about investing in technical skills), the non-individual, synchronous mode of IRL conferences crept into the top 3. Given that every other question elicited a top-3 of individual, asynchronous modes, this makes IRL conferences -- and group, synchronous modes in general -- seem like a bit of an outlier.

This raises the question: are individual, asynchronous learning modes the best ones devs could be using to invest in their careers? An efficient markets perspective would respond: "Absolutely. Your respondents aren't dumb, and they have the best data about what will produce good results for their careers, and they've incorporated this data into their decisions about how to invest." 

An innovation mindset would respond: "Maybe. But maybe there are more effective modes this group isn't using because these more effective modes aren't available, understood, or sufficiently adapted for the needs of software developers."
For now, this remains an open question, and one that invites further study.

# Method

In May 2019, I surveyed two groups of self-employed software developers. One group was a convenience opt-in sample from LinkedIn, and the other was a convenience opt-in sample from my ~2,000-member email list. I screened both samples by asking whether participants had spent time or money on career development in the last 2 years.

- 22 people from LinkedIn completed the survey.
- 33 people from my email list completed the survey.
- The median age of respondents is 42 (LinkedIn sample) and 41 (list sample).
- 64% of the LinkedIn sample have invested in their career in some way. 36% have not.
- 95% of the email list sample have invested in their career in some way. 5% have not. 

# Open data

You can inspect and use for your own purposes the anonymized survey responses generated by this research: <https://docs.google.com/spreadsheets/d/1QqOS6iqMEmk96sEUbNb6hm59PgQsCt9piSm82g19zDE/edit#gid=0>

# Discussion

I welcome discussion with you about the conclusions you might draw from this data, especially if they differ from mine. 

# Brought To You By Philip Morgan Consulting

I'm Philip Morgan, and I'm focused on helping dev shops cultivate, commercialize, and monetize expertise. 

There's an underlying tension inherent in this expertise project: what dev shops need to do to cultivate exceptionally valuable expertise is often in direct conflict with what they need to do to serve clients -- and generate revenue -- today. My work helps resolve this tension. 

Learn more: 
<https://philipmorganconsulting.com/research/>

