---
title: "Philip Morgan Consulting Research Briefing"
subtitle: "Managing remote developers"
author: "Philip Morgan"
date: November 6, 2019 - v0.8
abstract: |
  ABSTRACT TODO
fontsize: 13pt
urlcolor: blue
output:
  tufte::tufte_html:
    toc: true
    toc_depth: 2
  tufte::tufte_handout:
    toc: true
    toc_depth: 2
---

\newpage
The question at the heart of this study is simple: How large is the remote team you manage, why did you choose to work with remote developers, and what's difficult about it?

# Key Findings

1. F1
2. F2
3. F3
4. F4

\newpage
# All Findings

This research used a short, focused questionnaire. Below are the summarized responses to each question.

## Q: "In the last year, have you recommended working remotely to others?"

Of the 45 respondents who had managed dev team that is overseas OR a remote/distributed team that has just 2 or 3 hours/day of time zone overlap in the last year, 86.7% recommended it to others.

## Q: How many people are part of the team you manage?

| Number of team members | Count of respondents who indicated this team size  - % of respondents |
|:--------------|:-----------|
| 	5	 | 	8	 - 	17.78%	 |
| 	10	 | 	6	 - 	13.33%	 |
| 	2	 | 	4	 - 	8.89%	 |
| 	4	 | 	4	 - 	8.89%	 |
| 	12	 | 	3	 - 	6.67%	 |
| 	30	 | 	3	 - 	6.67%	 |
| 	6	 | 	2	 - 	4.44%	 |
| 	7	 | 	2	 - 	4.44%	 |
| 	9	 | 	2	 - 	4.44%	 |
| 	15	 | 	2	 - 	4.44%	 |
| 	400	 | 	1	 - 	2.22%	 |
| 	1	 | 	1	 - 	2.22%	 |
| 	3	 | 	1	 - 	2.22%	 |
| 	16	 | 	1	 - 	2.22%	 |
| 	20	 | 	1	 - 	2.22%	 |
| 	24	 | 	1	 - 	2.22%	 |
| 	70	 | 	1	 - 	2.22%	 |


```{r}
sizetable<-fread("size.csv",sep=",")
kable(sizetable, latex, digits = getOption("digits"), row.names = NA, col.names = NA, l, caption = NULL, label = NULL, format.args = list(), escape = TRUE)
library(plotly)
p <- plot_ly(sizetable, x = ~teamsize, y = ~respondents)
```

## Q: What is the #1 reason your company chose to hire remote developers?

I standardized the free-form answers to this question using a simple coding system. The tabulated coded responses are below. Note that some respondents provided more than one reason for choosing to hire remote developers.

| Reason | Count of respondents who indicated this reason - % of respondents |
|:--------------|:-----------|
| 	Better talent	 | 	17	 - 	37.78%	 |
| 	Cost	 | 	17	 - 	37.78%	 |
| 	Scaling ease	 | 	4	 - 	8.89%	 |
| 	More velocity	 | 	3	 - 	6.67%	 |
| 	Preserve existing relationship through relocation	 | 	3	 - 	6.67%	 |
| 	Lifestyle	 | 	1	 - 	2.22%	 |
| 	more reliability	 | 	1	 - 	2.22%	 |
| 	No physical location	 | 	1	 - 	2.22%	 |
| 	Quality	 | 	1	 - 	2.22%	 |
| 	Unique project requirement(s)	 | 	1	 - 	2.22%	 |


## Q: What seems to be more difficult when managing remote developers?

I standardized the free-form answers to this question using a simple coding system. The tabulated coded responses are below. Note that some respondents provided more than difficulty in managing remote developers.

| Reason | Count of respondents who indicated this difficulty - % of respondents |
|:--------------|:-----------|
| 	Communication	 | 	21	 - 	46.67%	 |
| 	Time zone overlap	 | 	8	 - 	17.78%	 |
| 	Management	 | 	7	 - 	15.56%	 |
| 	Team building	 | 	6	 - 	13.33%	 |
| 	Cultural differences	 | 	5	 - 	11.11%	 |
| 	Managing underperformers	 | 	3	 - 	6.67%	 |
| 	None	 | 	2	 - 	4.44%	 |
| 	Onboarding	 | 	2	 - 	4.44%	 |


# Insights

TODO

# Method

In May 2019, I surveyed a group of Tech Leads and VP's of Engineering from Computer Software, Internet, and Information Technology and Services companies. This group was a convenience opt-in sample recruited using LinkedIn. I screened respondents by asking "In the last year, have you managed a dev team that is overseas OR a remote/distributed team that has just 2 or 3 hours/day of time zone overlap with you?"

- 56 people from LinkedIn completed the survey. 45 (80%) moved beyond the screener question.

# Open data

You can inspect and use for your own purposes the anonymized survey responses generated by this research: <TODO>

# Discussion

I welcome discussion with you about the conclusions you might draw from this data, especially if they differ from mine. 

# Brought To You By Philip Morgan Consulting

I'm Philip Morgan, and I'm focused on helping dev shops cultivate, commercialize, and monetize expertise. 

There's an underlying tension inherent in this expertise project: what dev shops need to do to cultivate exceptionally valuable expertise is often in direct conflict with what they need to do to serve clients -- and generate revenue -- today. My work helps resolve this tension. 

Learn more: 
<https://philipmorganconsulting.com/research/>

Template stuff:

`r tufte::margin_note('MARGINNOTE WITHOUT FOOTNOTE NUMBER')`
